/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedChatbotRouteImport } from './routes/_authenticated/chatbot'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiPublicClientChatRouteImport } from './routes/api/public/client-chat'
import { Route as ApiPublicClientChatbotRouteImport } from './routes/api/public/client-chatbot'
import { Route as ApiPublicWidgetDotjsRouteImport } from './routes/api/public/widget[.]js'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatbotRoute = AuthenticatedChatbotRouteImport.update({
  id: '/chatbot', path: '/chatbot', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard', path: '/dashboard', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClientChatRoute = ApiPublicClientChatRouteImport.update({
  id: '/api/public/client-chat', path: '/api/public/client-chat', getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClientChatbotRoute = ApiPublicClientChatbotRouteImport.update({
  id: '/api/public/client-chatbot', path: '/api/public/client-chatbot', getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetDotjsRoute = ApiPublicWidgetDotjsRouteImport.update({
  id: '/api/public/widget.js', path: '/api/public/widget.js', getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/client-chat': typeof ApiPublicClientChatRoute
  '/api/public/client-chatbot': typeof ApiPublicClientChatbotRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/client-chat': typeof ApiPublicClientChatRoute
  '/api/public/client-chatbot': typeof ApiPublicClientChatbotRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/chatbot': typeof AuthenticatedChatbotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/client-chat': typeof ApiPublicClientChatRoute
  '/api/public/client-chatbot': typeof ApiPublicClientChatbotRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/account'
    | '/chatbot'
    | '/dashboard'
    | '/admin'
    | '/auth/reset-password'
    | '/checkout/return'
    | '/api/public/chat'
    | '/api/public/client-chat'
    | '/api/public/client-chatbot'
    | '/api/public/widget.js'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/account'
    | '/chatbot'
    | '/dashboard'
    | '/admin'
    | '/auth/reset-password'
    | '/checkout/return'
    | '/api/public/chat'
    | '/api/public/client-chat'
    | '/api/public/client-chatbot'
    | '/api/public/widget.js'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/chatbot'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin'
    | '/auth/reset-password'
    | '/checkout/return'
    | '/api/public/chat'
    | '/api/public/client-chat'
    | '/api/public/client-chatbot'
    | '/api/public/widget.js'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicClientChatRoute: typeof ApiPublicClientChatRoute
  ApiPublicClientChatbotRoute: typeof ApiPublicClientChatbotRoute
  ApiPublicWidgetDotjsRoute: typeof ApiPublicWidgetDotjsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot': {
      id: '/_authenticated/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AuthenticatedChatbotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/client-chat': {
      id: '/api/public/client-chat'
      path: '/api/public/client-chat'
      fullPath: '/api/public/client-chat'
      preLoaderRoute: typeof ApiPublicClientChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/client-chatbot': {
      id: '/api/public/client-chatbot'
      path: '/api/public/client-chatbot'
      fullPath: '/api/public/client-chatbot'
      preLoaderRoute: typeof ApiPublicClientChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget.js': {
      id: '/api/public/widget.js'
      path: '/api/public/widget.js'
      fullPath: '/api/public/widget.js'
      preLoaderRoute: typeof ApiPublicWidgetDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedChatbotRoute: typeof AuthenticatedChatbotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedChatbotRoute: AuthenticatedChatbotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicClientChatRoute: ApiPublicClientChatRoute,
  ApiPublicClientChatbotRoute: ApiPublicClientChatbotRoute,
  ApiPublicWidgetDotjsRoute: ApiPublicWidgetDotjsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
